### ISSUE TITLE
Deploy to Firebase

### ISSUE THREAD

**Issue by clarencecastillo** [ntuoss/hackoss-admin#6]
Moved from ntuoss/hackoss-admin-deprecated#1

Would be useful if we could have a staging build for this app up on Firebase so we can easily see its progress. I've created an app over there named `hackoss-admin`.

In later stages, we could set the subdomain as `admin.ntuoss.com` later once we've reached a stable build.

**Comment by ZaynJarvis** [comment]
You mean a hackoss-admin site on firebase?
I am actually using that for master branch.

**Comment by ZaynJarvis** [comment]
For deprecated one. It has nothing related to this repo. It is just a design being abandoned.

**Comment by clarencecastillo** [comment]
> You mean a hackoss-admin site on firebase?
> I am actually using that for master branch.

As in, it may not be firebase, but just a deployment of this application so we can use for demos or testing. Do you have the url?

> For deprecated one. It has nothing related to this repo. It is just a design being abandoned.

Got it. I just added that remark as I copied it over from that abandoned repository.

**Comment by ZaynJarvis** [comment]
You can refer to the pr there has a preview provided by netlify.

**Comment by clarencecastillo** [comment]
Yup, that works as well. Thanks!
